# This script is basically a replacement for tools::update_pkg_po to overcome
# some problems and add some features

update_po <- function(dir = ".", verbose = FALSE) {
  extract_gettext2pot <- function(pot_file, package, copyright, encoding,
                                  version, bugs, dir = ".", verbose = FALSE)
  {
    extract_gettext <- function(dir = ".", verbose = FALSE)
    {
      find_gettext_strings <- function(f)
      {
        e <- parse(file = f, keep.source = T)
        x <- getParseData(e)
        x |> dplyr::filter(
          token == "SYMBOL_FUNCTION_CALL" &
            text %in% c("gettext","gettextf")) |>
          dplyr::select(p1 = parent) |>
          dplyr::inner_join(x, dplyr::join_by("p1" == "id")) |>
          dplyr::select(p1, p2 = parent) |>
          dplyr::inner_join(x, dplyr::join_by("p2" == "parent")) |>
          dplyr::select(p1,p2,id) |>
          dplyr::inner_join(x, dplyr::join_by("id" == "parent")) |>
          dplyr::filter(token == "STR_CONST") |>
          dplyr::mutate(
            reference = paste0("#: ", sub(paste0("^", stringr::str_escape(tools::file_path_as_absolute(".")), "/?"), "", tools::file_path_as_absolute(f)), ":", line1),
            msgid = as.character(sapply(.data$text, \(x)sub("[ \t\n]*$", "", sub("^[ \t\n]*", "", eval(parse(text=x)))))),
            .keep = "none")
      }

      r_dir <- tools::file_path_as_absolute(dir) |> file.path("R")
      r_exts <- tools:::.make_file_exts("code")
      r_files <- tools::list_files_with_exts(r_dir, r_exts)
      for (os in c("unix", "windows")) {
        os_subdir <- file.path(r_dir, os)
        if (dir.exists(os_subdir))
          r_files <- c(r_files, tools::list_files_with_exts(os_subdir, r_exts))
      }
      out <- tibble::tibble()
      for (f in r_files) {
        if (verbose)
          message("Parsing ", sQuote(f), domain = NA)
        out <- out |>
          dplyr::bind_rows(find_gettext_strings(f))
      }
      out |>
        dplyr::filter(msgid != "") |>
        dplyr::mutate(msgid = ordered(.data$msgid, levels = unique(.data$msgid))) |>
        dplyr::group_by(msgid) |>
        dplyr::summarise(references = list(reference)) |>
        dplyr::arrange(msgid) |>
        dplyr::mutate(msgid = as.character(.data$msgid))
    }

    # Get the msgids via tools::xgettext and compare to ensure compatibility
    msgids <- unique(unlist(tools::xgettext(dir, asCall = FALSE)))
    msgids <- msgids[nzchar(msgids)]
    msgids_info <- extract_gettext(dir, verbose = verbose)
    msgids2 <- msgids_info |> dplyr::pull(msgid)
    if(length(msgids) != length(msgids2) || !all(msgids == msgids2))
      warning("The generated msgids differ from the ones generated by tools::xgettext")
    if(nrow(msgids_info) > 0)
      msgids_info <- msgids_info |> dplyr::mutate(msgid = shQuote(encodeString(.data$msgid), type = "cmd"))
    msgids_plural <- tools::xngettext(dir)
    msgids_plural_uniqe <- unique(unlist(msgids_plural))
    # ToDo: Read plurals with references
    pot_con <- file(pot_file, "wt")
    on.exit(close(pot_con))
    now <- Sys.time()
    writeLines(
      con = pot_con,
      c(
        sprintf('# %s Translation Template File.', package),
        sprintf('# Copyright (C) %s %s', format(now, "%Y"), copyright),
        sprintf('# This file is distributed under the same license as the %s package.', package),
        '#',
        'msgid ""',
        'msgstr ""',
        sprintf('"Project-Id-Version: %s %s\\n"', package, version),
        sprintf('"Report-Msgid-Bugs-To: %s\\n"', bugs),
        paste0('"POT-Creation-Date: ', format(now, "%Y-%m-%d %H:%M%z"),'\\n"'),
        '"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"',
        '"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"',
        '"Language-Team: LANGUAGE <LL@li.org>\\n"',
        '"Language: \\n"',
        '"MIME-Version: 1.0\\n"',
        sprintf('"Content-Type: text/plain; charset=%s\\n"', encoding),
        '"Content-Transfer-Encoding: 8bit\\n"',
        if (length(msgids_plural_uniqe) > 0) '"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\\n"'
      )
    )
    for (i in 1:nrow(msgids_info)) {
      msgid <- msgids_info[i,1]
      references <- unlist(msgids_info[i,2])
      writeLines(con = pot_con, c("", references, paste("msgid", msgid), 'msgstr ""'))
    }
    for (msgid_plural in msgids_plural)
      for (p in msgid_plural)
        if (p[1L] %in% msgids_plural_uniqe)
        {
          writeLines(
            con = con,
            c(
              "",
              paste(
                "msgid       ",
                shQuote(encodeString(p[1L]), type = "cmd")
              ),
              paste(
                "msgid_plural",
                shQuote(encodeString(p[2L]), type = "cmd")
              ),
              'msgstr[0]    ""',
              'msgstr[1]    ""'
            )
          )
          msgids_plural_uniqe <- msgids_plural_uniqe[-match(p, msgids_plural_uniqe)]
        }
  }

  collation_bkp <- Sys.getlocale("LC_COLLATE")
  on.exit(Sys.setlocale("LC_COLLATE", collation_bkp))
  Sys.setlocale("LC_COLLATE", "C")
  dir.create("po", FALSE)
  po_files <- list.files(path = "po", pattern = "^R-.+\\.pot?$",
                         full.names = TRUE)
  description_info <- read.dcf(
    "DESCRIPTION",
    fields = c("Package", "Version", "Bugs", "Authors@R", "Encoding"))
  package_name <- description_info[1L]
  version <- description_info[2L]
  bugs <- description_info[3L]
  copyright <- eval(parse(text=description_info[4L])) |>
    format(
      include = c("given","family","role"),
      braces = list(
        given=c('list(value="',''),
        role=c('", roles=c("','"))')),
      collapse = list(
        role='","')) |>
    sapply(\(x){
      item <- eval(parse(text=x));
      if("cph" %in% item$roles)
        item$value
      },
      USE.NAMES = FALSE) |>
    unlist() |>
    trimws()
  encoding <- description_info[5L]

  po_inst_dir <- file.path("inst", "po")
  tmp_file <- tempfile(fileext = "pot")
  on.exit(file.remove(tmp_file), add = TRUE, after = FALSE)
  if (verbose)
    message("Creating pot: .. ", domain = NA)

  extract_gettext2pot(pot_file = tmp_file, package = package_name, copyright, encoding,
                      version, bugs, dir, verbose)

  pot_file <- file.path("po", paste0("R-", package_name, ".pot"))
  if (verbose)
    message("Copying to potfile ", sQuote(pot_file), domain = NA)
  file.copy(tmp_file, pot_file, overwrite = TRUE)
  po_files <- po_files[!(po_files %in% c("po/R-en@quot.po", paste0("po/R-", package_name, ".pot")))]
  for (po_file in po_files) {
    language <- sub("^R-(.*)\\.po$", "\\1", basename(po_file))
    command <- "msgmerge"
    args <- c("--update", shQuote(po_file), shQuote(pot_file))
    has_warning <- FALSE
    warning_handler <- function(w) {
      environment(warning_handler)$has_warning <- TRUE
      tryInvokeRestart("muffleWarning")
    }

    if (verbose)
      message("Running command ", paste0(c(command, args), collapse = " "), appendLF = FALSE, domain = NA)
    else
      message(paste(command, language), appendLF = FALSE, domain = NA)

    result <- withCallingHandlers(system2(command, args, stderr = TRUE), warning = warning_handler)

    if (has_warning)
    {
      message(":\n  ", result, domain = NA)
      warning("Running ", command, " on ", sQuote(pot_file), " failed",
              domain = NA, immediate. = TRUE)
      next
    }
    else message(" ", result, domain = NA)

    po_check <- tools::checkPoFile(po_file, TRUE)
    if (nrow(po_check)) {
      print(po_check)
      message("not installing", domain = NA)
      next
    }
    lang_inst_dir <- file.path(po_inst_dir, language, "LC_MESSAGES")
    dir.create(lang_inst_dir, FALSE, TRUE)
    mo_file <- file.path(lang_inst_dir, sprintf("R-%s.mo", package_name))

    has_warning <- FALSE
    command <- "msgfmt"
    args <- c("-c", "--statistics", "-o", shQuote(mo_file), shQuote(po_file))

    if (verbose)
      message("Running command ", paste0(c(command, args), collapse = " "), appendLF = FALSE, domain = NA)
    else
      message(paste(command, language), appendLF = FALSE, domain = NA)

    result <- withCallingHandlers(system2(command, args, stderr = TRUE), warning = warning_handler)

    if (has_warning)
    {
      message("\n  ", result, domain = NA)
      warning("Running ", command, " on ", sQuote(pot_file), " failed",
              domain = NA, immediate. = TRUE)
      next
    }
    else message(" ... done.\n  ", result, domain = NA)
  }

  invisible()
}

update_po()
